import Link from 'next/link';

const LEARN_LINKS = [
  { href: '/roadmaps', label: 'Roadmaps' },
  { href: '/agents',   label: 'AI Agents' },
  { href: '/player',   label: 'Player'    },
];

const COMPANY_LINKS = [
  { href: '/about',   label: 'About'          },
  { href: '/privacy', label: 'Privacy Policy' },
  { href: '/terms',   label: 'Terms of Use'   },
];

export function Footer() {
  return (
    <footer
      className="border-t px-4 py-10 sm:px-6 lg:px-8"
      style={{ borderColor: 'var(--border)' }}
      aria-label="Site footer"
    >
      <div className="mx-auto max-w-5xl">
        <div className="grid gap-8 sm:grid-cols-3">

          {/* Brand */}
          <div>
            <p className="mb-1 text-sm font-bold" style={{ color: 'var(--text-1)' }}>
              SkillStream AI
            </p>
            <p className="text-xs leading-relaxed" style={{ color: 'var(--text-3)' }}>
              Audio learning roadmaps for every tech topic — generated by AI, narrated by Amazon Polly.
            </p>
          </div>

          {/* Learn */}
          <div>
            <p className="mb-3 text-xs font-semibold uppercase tracking-widest" style={{ color: 'var(--text-3)' }}>
              Learn
            </p>
            <ul className="flex flex-col gap-2">
              {LEARN_LINKS.map(({ href, label }) => (
                <li key={href}>
                  <Link
                    href={href}
                    className="text-sm transition-colors hover:underline"
                    style={{ color: 'var(--text-2)' }}
                  >
                    {label}
                  </Link>
                </li>
              ))}
            </ul>
          </div>

          {/* Company */}
          <div>
            <p className="mb-3 text-xs font-semibold uppercase tracking-widest" style={{ color: 'var(--text-3)' }}>
              Company
            </p>
            <ul className="flex flex-col gap-2">
              {COMPANY_LINKS.map(({ href, label }) => (
                <li key={href}>
                  <Link
                    href={href}
                    className="text-sm transition-colors hover:underline"
                    style={{ color: 'var(--text-2)' }}
                  >
                    {label}
                  </Link>
                </li>
              ))}
            </ul>
          </div>

        </div>

        {/* Bottom bar */}
        <div
          className="mt-8 flex flex-col items-center justify-between gap-2 border-t pt-6 text-center text-xs sm:flex-row sm:text-left"
          style={{ borderColor: 'var(--border)', color: 'var(--text-3)' }}
        >
          <p>© {new Date().getFullYear()} SkillStream AI — Built on AWS Bedrock &amp; Polly</p>
          <p>
            Use the{' '}
            <span style={{ color: 'var(--text-2)' }}>accessibility button (↘)</span>
            {' '}to adjust text size, motion &amp; contrast
          </p>
        </div>
      </div>
    </footer>
  );
}
