import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'About',
  description: 'Learn about SkillStream AI — an audio learning platform powered by AWS Bedrock, Amazon Polly, and agentic AI that turns any tech topic into a structured podcast course.',
  alternates: { canonical: '/about' },
};

const STACK = [
  { name: 'Amazon Bedrock',      desc: 'Generates roadmap syllabuses and episode scripts using Nova and Claude models.' },
  { name: 'Amazon Polly',        desc: 'Narrates each episode as natural-sounding audio in seconds.' },
  { name: 'AWS Step Functions',  desc: 'Orchestrates the parallel script-and-audio generation pipeline.' },
  { name: 'Amazon DynamoDB',     desc: 'Stores roadmaps, episodes, and progress data with single-digit ms latency.' },
  { name: 'AWS Amplify',         desc: 'Hosts and auto-deploys the frontend on every push to main.' },
  { name: 'Strands Agents',      desc: 'Powers the Trend Discovery agent that surfaces what developers are learning now.' },
];

const HOW_IT_WORKS = [
  { step: '01', title: 'Pick a topic',     desc: 'Enter any technology — Rust, Kubernetes, LLM Engineering, anything — and SkillStream AI generates a structured roadmap in seconds.' },
  { step: '02', title: 'AI writes scripts', desc: 'Amazon Bedrock breaks the roadmap into episodes and writes a focused 5–10 minute script for each one, ordered from foundations to expert level.' },
  { step: '03', title: 'Polly narrates',   desc: 'Amazon Polly converts each script into clear, natural-sounding audio — ready to stream immediately, no waiting.' },
  { step: '04', title: 'Agents keep it fresh', desc: 'The Trend Discovery agent monitors the tech world continuously and adds new episodes on emerging topics automatically.' },
];

export default function AboutPage() {
  return (
    <div>
      {/* Hero */}
      <div className="hero-gradient border-b border-[var(--border)] px-4 pt-20 pb-12 sm:px-6 lg:px-8">
        <div className="mx-auto max-w-3xl">
          <p className="mb-2 text-xs font-semibold uppercase tracking-widest text-[var(--amber)]">
            About
          </p>
          <h1 className="text-3xl font-bold text-[var(--text-1)] sm:text-4xl">
            About SkillStream AI
          </h1>
          <p className="mt-3 text-sm text-[var(--text-2)] sm:text-base">
            An audio-first learning platform that turns any technology topic into a structured, narrated course — built entirely on AWS.
          </p>
        </div>
      </div>

      <div className="mx-auto max-w-3xl px-4 py-8 sm:px-6 lg:px-8 space-y-6">

        {/* Mission */}
        <div className="glass-panel p-6 sm:p-8">
          <h2 className="mb-3 text-base font-bold text-[var(--text-1)]">What we build</h2>
          <p className="text-sm leading-relaxed text-[var(--text-2)]">
            SkillStream AI makes technical learning fit into real life. Instead of sitting down with a textbook or a 40-hour video course, you listen. We take any tech topic — a language, a cloud service, an architecture pattern — and produce a podcast-style curriculum: hierarchical, opinionated, and narrated.
          </p>
          <p className="mt-3 text-sm leading-relaxed text-[var(--text-2)]">
            Every roadmap is generated by AI, every episode is written and narrated by AI, and every new trending topic is discovered by AI agents that run around the clock. The result is a library that grows and stays current without manual curation.
          </p>
        </div>

        {/* How it works */}
        <div className="glass-panel p-6 sm:p-8">
          <h2 className="mb-5 text-base font-bold text-[var(--text-1)]">How it works</h2>
          <div className="flex flex-col gap-5">
            {HOW_IT_WORKS.map(({ step, title, desc }) => (
              <div key={step} className="flex gap-4">
                <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full border border-[var(--amber)]/30 bg-[var(--amber)]/10 text-xs font-bold text-[var(--amber)]">
                  {step}
                </div>
                <div>
                  <p className="text-sm font-semibold text-[var(--text-1)]">{title}</p>
                  <p className="mt-0.5 text-sm leading-relaxed text-[var(--text-2)]">{desc}</p>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* The stack */}
        <div className="glass-panel p-6 sm:p-8">
          <h2 className="mb-5 text-base font-bold text-[var(--text-1)]">The stack</h2>
          <div className="grid gap-4 sm:grid-cols-2">
            {STACK.map(({ name, desc }) => (
              <div key={name} className="rounded-xl border border-[var(--border)] bg-[var(--surface-2)] p-4">
                <p className="text-xs font-semibold text-[var(--amber)]">{name}</p>
                <p className="mt-1 text-xs leading-relaxed text-[var(--text-2)]">{desc}</p>
              </div>
            ))}
          </div>
        </div>

      </div>
    </div>
  );
}
