import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Use',
  description: 'Terms of Use for SkillStream AI — the conditions under which you may use the platform.',
  alternates: { canonical: '/terms' },
};

const EFFECTIVE_DATE = 'March 2025';

function Section({ title, children }: Readonly<{ title: string; children: React.ReactNode }>) {
  return (
    <div className="glass-panel p-6 sm:p-8">
      <h2 className="mb-3 text-base font-bold text-[var(--text-1)]">{title}</h2>
      <div className="space-y-2 text-sm leading-relaxed text-[var(--text-2)]">
        {children}
      </div>
    </div>
  );
}

export default function TermsPage() {
  return (
    <div>
      {/* Hero */}
      <div className="hero-gradient border-b border-[var(--border)] px-4 pt-20 pb-12 sm:px-6 lg:px-8">
        <div className="mx-auto max-w-3xl">
          <p className="mb-2 text-xs font-semibold uppercase tracking-widest text-[var(--amber)]">
            Legal
          </p>
          <h1 className="text-3xl font-bold text-[var(--text-1)] sm:text-4xl">
            Terms of Use
          </h1>
          <p className="mt-3 text-sm text-[var(--text-2)]">
            Effective date: {EFFECTIVE_DATE}
          </p>
        </div>
      </div>

      <div className="mx-auto max-w-3xl px-4 py-8 sm:px-6 lg:px-8 space-y-6">

        <Section title="Acceptance of terms">
          <p>
            By accessing or using SkillStream AI (&quot;the Service&quot;), you agree to be bound by these Terms of Use. If you do not agree to these terms, please do not use the Service.
          </p>
          <p>
            These terms apply to all visitors, users, and anyone who accesses the Service.
          </p>
        </Section>

        <Section title="Use of the Service">
          <p>You may use SkillStream AI for personal, non-commercial learning purposes. You agree not to:</p>
          <ul className="ml-4 list-disc space-y-1">
            <li>Use the Service in any way that violates applicable laws or regulations.</li>
            <li>Attempt to gain unauthorised access to any part of the Service or its backend infrastructure.</li>
            <li>Scrape, harvest, or systematically download content from the Service at scale without prior permission.</li>
            <li>Use the Service to generate content that is harmful, illegal, or misleading.</li>
            <li>Interfere with or disrupt the integrity or performance of the Service.</li>
          </ul>
        </Section>

        <Section title="AI-generated content">
          <p>
            All roadmaps, episode scripts, and audio narrations on SkillStream AI are generated by artificial intelligence, including Amazon Bedrock language models and Amazon Polly text-to-speech. While we strive for accuracy:
          </p>
          <ul className="ml-4 list-disc space-y-1">
            <li>AI-generated content may contain errors, inaccuracies, or outdated information.</li>
            <li>Content should not be relied upon as a substitute for professional advice in critical domains (security, medical, legal, financial).</li>
            <li>Topics generated by the Trend Discovery agent reflect publicly available internet data and may not be comprehensive or unbiased.</li>
          </ul>
          <p>
            We recommend verifying important technical details with official documentation and authoritative sources.
          </p>
        </Section>

        <Section title="Intellectual property">
          <p>
            The SkillStream AI platform, including its interface design, source code, and branding, is the property of its creators. AI-generated roadmap and episode content is produced on demand and is not independently owned.
          </p>
          <p>
            You may use content from SkillStream AI for personal learning. Redistribution or commercial use of generated content without permission is not permitted.
          </p>
        </Section>

        <Section title="Disclaimer of warranties">
          <p>
            The Service is provided &quot;as is&quot; and &quot;as available&quot; without any warranties of any kind, either express or implied. We do not warrant that the Service will be uninterrupted, error-free, or that generated content will be accurate or complete.
          </p>
        </Section>

        <Section title="Limitation of liability">
          <p>
            To the fullest extent permitted by law, SkillStream AI and its creators shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Service, including but not limited to errors in AI-generated content, service interruptions, or data loss.
          </p>
        </Section>

        <Section title="Changes to these terms">
          <p>
            We reserve the right to modify these Terms of Use at any time. Changes are effective immediately upon posting at this URL. Continued use of the Service after changes constitutes acceptance of the revised terms.
          </p>
        </Section>

        <Section title="Contact">
          <p>
            If you have questions about these Terms of Use, please open an issue in the project&apos;s GitHub repository.
          </p>
        </Section>

      </div>
    </div>
  );
}
